webtalk_init -webtalk_dir C:/Users/GSRAJA/Desktop/IIT GN/sem 4/ES 204/Project/code3/iter3/iter3.sim/sim_1/behav/xsim/xsim.dir/tb_matrix_mult_8x8_q88_dsp_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr  2 15:34:41 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e2b653c6-24f7-46f8-a038-a2ecb80f2909" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a1cc2ddc642e4c418a88123e63ad7261" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "212900 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8568_KB" -context "xsim\\usage"
webtalk_transmit -clientid 964104714 -regid "" -xml C:/Users/GSRAJA/Desktop/IIT GN/sem 4/ES 204/Project/code3/iter3/iter3.sim/sim_1/behav/xsim/xsim.dir/tb_matrix_mult_8x8_q88_dsp_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/GSRAJA/Desktop/IIT GN/sem 4/ES 204/Project/code3/iter3/iter3.sim/sim_1/behav/xsim/xsim.dir/tb_matrix_mult_8x8_q88_dsp_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/GSRAJA/Desktop/IIT GN/sem 4/ES 204/Project/code3/iter3/iter3.sim/sim_1/behav/xsim/xsim.dir/tb_matrix_mult_8x8_q88_dsp_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
